### ISSUE TITLE
Missing label io.buildpacks.builder.metadata

### ISSUE THREAD

**Issue by liangyuanpeng** [paketo-community/cargo#150]
Try buildpack for my cargo project from this builder and just failed.  

```
lan@lan:~/repo/git/czechwd$ pack build test -B paketocommunity/cargo:latest
latest: Pulling from paketocommunity/cargo
8c0fd3710fbf: Pull complete 
Digest: sha256:e5e6e38be403d305d996cd45230b7e1f7bd17ea7d121f7a62e6f4cec788e4dff
Status: Downloaded newer image for paketocommunity/cargo:latest
ERROR: failed to build: invalid builder paketocommunity/cargo:latest: builder index.docker.io/paketocommunity/cargo:latest missing label io.buildpacks.builder.metadata -- try recreating builder
```  

pack version : 0.23.0+git-0db2c77.build-3056

Maybe i missed something, remind me if i missed some doc, thanks!

**Comment by dmikusa-pivotal** [comment]
>`pack build test -B paketocommunity/cargo:latest`

This isn't the right command to run. The `-B` flag sets a builder, but you're pointing to a buildpack. 

We do not publish a Rust builder, but we do publish a Rust builder descriptor file so you can easily create your own builder. See here for [instructions to build your own builder](https://github.com/paketo-community/rust#a-builder). It's one command to run. It will produce an image and you can reference that image with the `-B` flag.

Alternative, if you want to use the Rust buildpack directly you can run `pack build test -b paketocommunity/rust` (note the lower case `b`). We do publish public images of the Rust buildpack so that can be an option if you do not want to build your own builder.

The difference with the builder is that you can control the stack (build & run images), if you want to customize them.
